pipeline:
  inputs:
    - name: http
      port: 8888

      processors:
        logs:
          # only start processors for specific hostnames
          - name: lua
            script: dswm.lua
            call: filter_on_hostname

          # get the reqTimSec and set as TIMESTAMP in the event
          - name: lua
            script: dswm.lua
            call: set_timestamp

          # add timestamp to our MESSAGE
          - name: lua
            script: dswm.lua
            call: convert_time

          # set severity number in MESSAGE based on HTTP status code
          - name: lua
            script: dswm.lua
            call: set_severity_number

          # convert anything to a number that looks like a number in the MESSAGE
          - name: lua
            script: dswm.lua
            call: convert_to_numbers

          # create some nice otel message
          - name: opentelemetry_envelope

          # set otel resources service name
          - name: content_modifier
            context: otel_resource_attributes
            action: insert
            key: "service.name"
            value: "akamai-datastream"

          # set otel version resource version, default to 1.
          - name: content_modifier
            context: otel_resource_attributes
            action: insert
            key: "service.version"
            value: "1"

  outputs:
    - name: stdout
      match: ds.log

    - name: opentelemetry
      match: "*"
      host: 127.0.0.1
      port: 4318
      logs_severity_number_message_key: severityNumber
      logs_trace_id_message_key: reqId
